2024-10-19 08:13:19 - Error: CUDA out of memory. Tried to allocate 9.07 GiB. GPU 0 has a total capacity of 23.68 GiB of which 2.14 GiB is free. Including non-PyTorch memory, this process has 21.53 GiB memory in use. Of the allocated memory 17.57 GiB is allocated by PyTorch, and 3.66 GiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
Traceback (most recent call last):
  File "/home/nguyen/code/nguyen/uit-ds/src/agent/reasoning.py", line 150, in Reasoning
    reasonings = prompt_creator.generation(
  File "/home/nguyen/miniconda3/envs/uit-ds/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/home/nguyen/code/nguyen/uit-ds/src/agent/reasoning.py", line 95, in generation
    generated_ids = self.model.generate(**inputs, **self.generation_config)
  File "/home/nguyen/miniconda3/envs/uit-ds/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/home/nguyen/miniconda3/envs/uit-ds/lib/python3.10/site-packages/transformers/generation/utils.py", line 2047, in generate
    result = self._sample(
  File "/home/nguyen/miniconda3/envs/uit-ds/lib/python3.10/site-packages/transformers/generation/utils.py", line 3007, in _sample
    outputs = self(**model_inputs, return_dict=True)
  File "/home/nguyen/miniconda3/envs/uit-ds/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/nguyen/miniconda3/envs/uit-ds/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/nguyen/miniconda3/envs/uit-ds/lib/python3.10/site-packages/accelerate/hooks.py", line 170, in new_forward
    output = module._old_forward(*args, **kwargs)
  File "/home/nguyen/miniconda3/envs/uit-ds/lib/python3.10/site-packages/transformers/models/qwen2_vl/modeling_qwen2_vl.py", line 1691, in forward
    image_embeds = self.visual(pixel_values, grid_thw=image_grid_thw)
  File "/home/nguyen/miniconda3/envs/uit-ds/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/nguyen/miniconda3/envs/uit-ds/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/nguyen/miniconda3/envs/uit-ds/lib/python3.10/site-packages/accelerate/hooks.py", line 170, in new_forward
    output = module._old_forward(*args, **kwargs)
  File "/home/nguyen/miniconda3/envs/uit-ds/lib/python3.10/site-packages/transformers/models/qwen2_vl/modeling_qwen2_vl.py", line 1128, in forward
    hidden_states = blk(hidden_states, cu_seqlens=cu_seqlens, rotary_pos_emb=rotary_pos_emb)
  File "/home/nguyen/miniconda3/envs/uit-ds/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/nguyen/miniconda3/envs/uit-ds/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/nguyen/miniconda3/envs/uit-ds/lib/python3.10/site-packages/accelerate/hooks.py", line 170, in new_forward
    output = module._old_forward(*args, **kwargs)
  File "/home/nguyen/miniconda3/envs/uit-ds/lib/python3.10/site-packages/transformers/models/qwen2_vl/modeling_qwen2_vl.py", line 431, in forward
    hidden_states = hidden_states + self.attn(
  File "/home/nguyen/miniconda3/envs/uit-ds/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/nguyen/miniconda3/envs/uit-ds/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/nguyen/miniconda3/envs/uit-ds/lib/python3.10/site-packages/accelerate/hooks.py", line 170, in new_forward
    output = module._old_forward(*args, **kwargs)
  File "/home/nguyen/miniconda3/envs/uit-ds/lib/python3.10/site-packages/transformers/models/qwen2_vl/modeling_qwen2_vl.py", line 404, in forward
    attn_output = F.scaled_dot_product_attention(q, k, v, attention_mask, dropout_p=0.0)
torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 9.07 GiB. GPU 0 has a total capacity of 23.68 GiB of which 2.14 GiB is free. Including non-PyTorch memory, this process has 21.53 GiB memory in use. Of the allocated memory 17.57 GiB is allocated by PyTorch, and 3.66 GiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)

2024-10-19 08:13:41 - Error: CUDA out of memory. Tried to allocate 5.12 GiB. GPU 0 has a total capacity of 23.68 GiB of which 2.15 GiB is free. Including non-PyTorch memory, this process has 21.53 GiB memory in use. Of the allocated memory 13.08 GiB is allocated by PyTorch, and 8.14 GiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
Traceback (most recent call last):
  File "/home/nguyen/code/nguyen/uit-ds/src/agent/reasoning.py", line 150, in Reasoning
    reasonings = prompt_creator.generation(
  File "/home/nguyen/miniconda3/envs/uit-ds/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/home/nguyen/code/nguyen/uit-ds/src/agent/reasoning.py", line 95, in generation
    generated_ids = self.model.generate(**inputs, **self.generation_config)
  File "/home/nguyen/miniconda3/envs/uit-ds/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/home/nguyen/miniconda3/envs/uit-ds/lib/python3.10/site-packages/transformers/generation/utils.py", line 2047, in generate
    result = self._sample(
  File "/home/nguyen/miniconda3/envs/uit-ds/lib/python3.10/site-packages/transformers/generation/utils.py", line 3007, in _sample
    outputs = self(**model_inputs, return_dict=True)
  File "/home/nguyen/miniconda3/envs/uit-ds/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/nguyen/miniconda3/envs/uit-ds/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/nguyen/miniconda3/envs/uit-ds/lib/python3.10/site-packages/accelerate/hooks.py", line 170, in new_forward
    output = module._old_forward(*args, **kwargs)
  File "/home/nguyen/miniconda3/envs/uit-ds/lib/python3.10/site-packages/transformers/models/qwen2_vl/modeling_qwen2_vl.py", line 1691, in forward
    image_embeds = self.visual(pixel_values, grid_thw=image_grid_thw)
  File "/home/nguyen/miniconda3/envs/uit-ds/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/nguyen/miniconda3/envs/uit-ds/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/nguyen/miniconda3/envs/uit-ds/lib/python3.10/site-packages/accelerate/hooks.py", line 170, in new_forward
    output = module._old_forward(*args, **kwargs)
  File "/home/nguyen/miniconda3/envs/uit-ds/lib/python3.10/site-packages/transformers/models/qwen2_vl/modeling_qwen2_vl.py", line 1128, in forward
    hidden_states = blk(hidden_states, cu_seqlens=cu_seqlens, rotary_pos_emb=rotary_pos_emb)
  File "/home/nguyen/miniconda3/envs/uit-ds/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/nguyen/miniconda3/envs/uit-ds/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/nguyen/miniconda3/envs/uit-ds/lib/python3.10/site-packages/accelerate/hooks.py", line 170, in new_forward
    output = module._old_forward(*args, **kwargs)
  File "/home/nguyen/miniconda3/envs/uit-ds/lib/python3.10/site-packages/transformers/models/qwen2_vl/modeling_qwen2_vl.py", line 431, in forward
    hidden_states = hidden_states + self.attn(
  File "/home/nguyen/miniconda3/envs/uit-ds/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/nguyen/miniconda3/envs/uit-ds/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/nguyen/miniconda3/envs/uit-ds/lib/python3.10/site-packages/accelerate/hooks.py", line 170, in new_forward
    output = module._old_forward(*args, **kwargs)
  File "/home/nguyen/miniconda3/envs/uit-ds/lib/python3.10/site-packages/transformers/models/qwen2_vl/modeling_qwen2_vl.py", line 404, in forward
    attn_output = F.scaled_dot_product_attention(q, k, v, attention_mask, dropout_p=0.0)
torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 5.12 GiB. GPU 0 has a total capacity of 23.68 GiB of which 2.15 GiB is free. Including non-PyTorch memory, this process has 21.53 GiB memory in use. Of the allocated memory 13.08 GiB is allocated by PyTorch, and 8.14 GiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)

2024-10-19 08:13:46 - Error: CUDA out of memory. Tried to allocate 4.54 GiB. GPU 0 has a total capacity of 23.68 GiB of which 2.22 GiB is free. Including non-PyTorch memory, this process has 21.45 GiB memory in use. Of the allocated memory 11.82 GiB is allocated by PyTorch, and 9.32 GiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
Traceback (most recent call last):
  File "/home/nguyen/code/nguyen/uit-ds/src/agent/reasoning.py", line 150, in Reasoning
    reasonings = prompt_creator.generation(
  File "/home/nguyen/miniconda3/envs/uit-ds/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/home/nguyen/code/nguyen/uit-ds/src/agent/reasoning.py", line 95, in generation
    generated_ids = self.model.generate(**inputs, **self.generation_config)
  File "/home/nguyen/miniconda3/envs/uit-ds/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/home/nguyen/miniconda3/envs/uit-ds/lib/python3.10/site-packages/transformers/generation/utils.py", line 2047, in generate
    result = self._sample(
  File "/home/nguyen/miniconda3/envs/uit-ds/lib/python3.10/site-packages/transformers/generation/utils.py", line 3014, in _sample
    next_token_logits = outputs.logits.clone()[:, -1, :].float()
torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 4.54 GiB. GPU 0 has a total capacity of 23.68 GiB of which 2.22 GiB is free. Including non-PyTorch memory, this process has 21.45 GiB memory in use. Of the allocated memory 11.82 GiB is allocated by PyTorch, and 9.32 GiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)

2024-10-19 08:14:40 - Error: CUDA out of memory. Tried to allocate 4.76 GiB. GPU 0 has a total capacity of 23.68 GiB of which 2.22 GiB is free. Including non-PyTorch memory, this process has 21.45 GiB memory in use. Of the allocated memory 12.06 GiB is allocated by PyTorch, and 9.09 GiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
Traceback (most recent call last):
  File "/home/nguyen/code/nguyen/uit-ds/src/agent/reasoning.py", line 150, in Reasoning
    reasonings = prompt_creator.generation(
  File "/home/nguyen/miniconda3/envs/uit-ds/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/home/nguyen/code/nguyen/uit-ds/src/agent/reasoning.py", line 95, in generation
    generated_ids = self.model.generate(**inputs, **self.generation_config)
  File "/home/nguyen/miniconda3/envs/uit-ds/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/home/nguyen/miniconda3/envs/uit-ds/lib/python3.10/site-packages/transformers/generation/utils.py", line 2047, in generate
    result = self._sample(
  File "/home/nguyen/miniconda3/envs/uit-ds/lib/python3.10/site-packages/transformers/generation/utils.py", line 3014, in _sample
    next_token_logits = outputs.logits.clone()[:, -1, :].float()
torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 4.76 GiB. GPU 0 has a total capacity of 23.68 GiB of which 2.22 GiB is free. Including non-PyTorch memory, this process has 21.45 GiB memory in use. Of the allocated memory 12.06 GiB is allocated by PyTorch, and 9.09 GiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)

2024-10-19 08:15:34 - Error: CUDA out of memory. Tried to allocate 4.67 GiB. GPU 0 has a total capacity of 23.68 GiB of which 1.97 GiB is free. Including non-PyTorch memory, this process has 21.70 GiB memory in use. Of the allocated memory 11.96 GiB is allocated by PyTorch, and 9.43 GiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
Traceback (most recent call last):
  File "/home/nguyen/code/nguyen/uit-ds/src/agent/reasoning.py", line 150, in Reasoning
    reasonings = prompt_creator.generation(
  File "/home/nguyen/miniconda3/envs/uit-ds/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/home/nguyen/code/nguyen/uit-ds/src/agent/reasoning.py", line 95, in generation
    generated_ids = self.model.generate(**inputs, **self.generation_config)
  File "/home/nguyen/miniconda3/envs/uit-ds/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/home/nguyen/miniconda3/envs/uit-ds/lib/python3.10/site-packages/transformers/generation/utils.py", line 2047, in generate
    result = self._sample(
  File "/home/nguyen/miniconda3/envs/uit-ds/lib/python3.10/site-packages/transformers/generation/utils.py", line 3014, in _sample
    next_token_logits = outputs.logits.clone()[:, -1, :].float()
torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 4.67 GiB. GPU 0 has a total capacity of 23.68 GiB of which 1.97 GiB is free. Including non-PyTorch memory, this process has 21.70 GiB memory in use. Of the allocated memory 11.96 GiB is allocated by PyTorch, and 9.43 GiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)

2024-10-19 08:16:02 - Error: CUDA out of memory. Tried to allocate 4.97 GiB. GPU 0 has a total capacity of 23.68 GiB of which 1.97 GiB is free. Including non-PyTorch memory, this process has 21.70 GiB memory in use. Of the allocated memory 12.26 GiB is allocated by PyTorch, and 9.13 GiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
Traceback (most recent call last):
  File "/home/nguyen/code/nguyen/uit-ds/src/agent/reasoning.py", line 150, in Reasoning
    for batch in tqdm(get_n_items_at_a_time(data, batch), total=total_batches):
  File "/home/nguyen/miniconda3/envs/uit-ds/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/home/nguyen/code/nguyen/uit-ds/src/agent/reasoning.py", line 95, in generation
    inputs = self.prompt_creator(image_path, caption, label, ocr).to(self.model.device)
  File "/home/nguyen/miniconda3/envs/uit-ds/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/home/nguyen/miniconda3/envs/uit-ds/lib/python3.10/site-packages/transformers/generation/utils.py", line 2047, in generate
    result = self._sample(
  File "/home/nguyen/miniconda3/envs/uit-ds/lib/python3.10/site-packages/transformers/generation/utils.py", line 3014, in _sample
    next_token_logits = outputs.logits.clone()[:, -1, :].float()
torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 4.97 GiB. GPU 0 has a total capacity of 23.68 GiB of which 1.97 GiB is free. Including non-PyTorch memory, this process has 21.70 GiB memory in use. Of the allocated memory 12.26 GiB is allocated by PyTorch, and 9.13 GiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)

2024-10-19 08:16:08 - Error: CUDA out of memory. Tried to allocate 5.69 GiB. GPU 0 has a total capacity of 23.68 GiB of which 2.02 GiB is free. Including non-PyTorch memory, this process has 21.65 GiB memory in use. Of the allocated memory 13.02 GiB is allocated by PyTorch, and 8.32 GiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
Traceback (most recent call last):
  File "/home/nguyen/code/nguyen/uit-ds/src/agent/reasoning.py", line 150, in Reasoning
    for batch in tqdm(get_n_items_at_a_time(data, batch), total=total_batches):
  File "/home/nguyen/miniconda3/envs/uit-ds/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/home/nguyen/code/nguyen/uit-ds/src/agent/reasoning.py", line 95, in generation
    inputs = self.prompt_creator(image_path, caption, label, ocr).to(self.model.device)
  File "/home/nguyen/miniconda3/envs/uit-ds/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/home/nguyen/miniconda3/envs/uit-ds/lib/python3.10/site-packages/transformers/generation/utils.py", line 2047, in generate
    result = self._sample(
  File "/home/nguyen/miniconda3/envs/uit-ds/lib/python3.10/site-packages/transformers/generation/utils.py", line 3014, in _sample
    next_token_logits = outputs.logits.clone()[:, -1, :].float()
torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 5.69 GiB. GPU 0 has a total capacity of 23.68 GiB of which 2.02 GiB is free. Including non-PyTorch memory, this process has 21.65 GiB memory in use. Of the allocated memory 13.02 GiB is allocated by PyTorch, and 8.32 GiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)

2024-10-19 09:25:44 - Error: CUDA out of memory. Tried to allocate 9.07 GiB. GPU 0 has a total capacity of 23.68 GiB of which 5.61 GiB is free. Including non-PyTorch memory, this process has 18.07 GiB memory in use. Of the allocated memory 17.57 GiB is allocated by PyTorch, and 197.16 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
Traceback (most recent call last):
  File "/home/nguyen/code/nguyen/uit-ds/src/agent/reasoning.py", line 153, in Reasoning
    reasonings = prompt_creator.generation(
  File "/home/nguyen/miniconda3/envs/uit-ds/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/home/nguyen/code/nguyen/uit-ds/src/agent/reasoning.py", line 96, in generation
    generated_ids = self.model.generate(**inputs, **self.generation_config)
  File "/home/nguyen/miniconda3/envs/uit-ds/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/home/nguyen/miniconda3/envs/uit-ds/lib/python3.10/site-packages/transformers/generation/utils.py", line 2047, in generate
    result = self._sample(
  File "/home/nguyen/miniconda3/envs/uit-ds/lib/python3.10/site-packages/transformers/generation/utils.py", line 3007, in _sample
    outputs = self(**model_inputs, return_dict=True)
  File "/home/nguyen/miniconda3/envs/uit-ds/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/nguyen/miniconda3/envs/uit-ds/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/nguyen/miniconda3/envs/uit-ds/lib/python3.10/site-packages/accelerate/hooks.py", line 170, in new_forward
    output = module._old_forward(*args, **kwargs)
  File "/home/nguyen/miniconda3/envs/uit-ds/lib/python3.10/site-packages/transformers/models/qwen2_vl/modeling_qwen2_vl.py", line 1691, in forward
    image_embeds = self.visual(pixel_values, grid_thw=image_grid_thw)
  File "/home/nguyen/miniconda3/envs/uit-ds/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/nguyen/miniconda3/envs/uit-ds/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/nguyen/miniconda3/envs/uit-ds/lib/python3.10/site-packages/accelerate/hooks.py", line 170, in new_forward
    output = module._old_forward(*args, **kwargs)
  File "/home/nguyen/miniconda3/envs/uit-ds/lib/python3.10/site-packages/transformers/models/qwen2_vl/modeling_qwen2_vl.py", line 1128, in forward
    hidden_states = blk(hidden_states, cu_seqlens=cu_seqlens, rotary_pos_emb=rotary_pos_emb)
  File "/home/nguyen/miniconda3/envs/uit-ds/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/nguyen/miniconda3/envs/uit-ds/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/nguyen/miniconda3/envs/uit-ds/lib/python3.10/site-packages/accelerate/hooks.py", line 170, in new_forward
    output = module._old_forward(*args, **kwargs)
  File "/home/nguyen/miniconda3/envs/uit-ds/lib/python3.10/site-packages/transformers/models/qwen2_vl/modeling_qwen2_vl.py", line 431, in forward
    hidden_states = hidden_states + self.attn(
  File "/home/nguyen/miniconda3/envs/uit-ds/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/nguyen/miniconda3/envs/uit-ds/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/nguyen/miniconda3/envs/uit-ds/lib/python3.10/site-packages/accelerate/hooks.py", line 170, in new_forward
    output = module._old_forward(*args, **kwargs)
  File "/home/nguyen/miniconda3/envs/uit-ds/lib/python3.10/site-packages/transformers/models/qwen2_vl/modeling_qwen2_vl.py", line 404, in forward
    attn_output = F.scaled_dot_product_attention(q, k, v, attention_mask, dropout_p=0.0)
torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 9.07 GiB. GPU 0 has a total capacity of 23.68 GiB of which 5.61 GiB is free. Including non-PyTorch memory, this process has 18.07 GiB memory in use. Of the allocated memory 17.57 GiB is allocated by PyTorch, and 197.16 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)

2024-10-19 09:27:00 - Error: CUDA out of memory. Tried to allocate 9.07 GiB. GPU 0 has a total capacity of 23.68 GiB of which 5.61 GiB is free. Including non-PyTorch memory, this process has 18.07 GiB memory in use. Of the allocated memory 17.57 GiB is allocated by PyTorch, and 197.16 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
Traceback (most recent call last):
  File "/home/nguyen/code/nguyen/uit-ds/src/agent/reasoning.py", line 153, in Reasoning
    reasonings = prompt_creator.generation(
  File "/home/nguyen/miniconda3/envs/uit-ds/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/home/nguyen/code/nguyen/uit-ds/src/agent/reasoning.py", line 96, in generation
    generated_ids = self.model.generate(**inputs, **self.generation_config)
  File "/home/nguyen/miniconda3/envs/uit-ds/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/home/nguyen/miniconda3/envs/uit-ds/lib/python3.10/site-packages/transformers/generation/utils.py", line 2047, in generate
    result = self._sample(
  File "/home/nguyen/miniconda3/envs/uit-ds/lib/python3.10/site-packages/transformers/generation/utils.py", line 3007, in _sample
    outputs = self(**model_inputs, return_dict=True)
  File "/home/nguyen/miniconda3/envs/uit-ds/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/nguyen/miniconda3/envs/uit-ds/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/nguyen/miniconda3/envs/uit-ds/lib/python3.10/site-packages/accelerate/hooks.py", line 170, in new_forward
    output = module._old_forward(*args, **kwargs)
  File "/home/nguyen/miniconda3/envs/uit-ds/lib/python3.10/site-packages/transformers/models/qwen2_vl/modeling_qwen2_vl.py", line 1691, in forward
    image_embeds = self.visual(pixel_values, grid_thw=image_grid_thw)
  File "/home/nguyen/miniconda3/envs/uit-ds/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/nguyen/miniconda3/envs/uit-ds/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/nguyen/miniconda3/envs/uit-ds/lib/python3.10/site-packages/accelerate/hooks.py", line 170, in new_forward
    output = module._old_forward(*args, **kwargs)
  File "/home/nguyen/miniconda3/envs/uit-ds/lib/python3.10/site-packages/transformers/models/qwen2_vl/modeling_qwen2_vl.py", line 1128, in forward
    hidden_states = blk(hidden_states, cu_seqlens=cu_seqlens, rotary_pos_emb=rotary_pos_emb)
  File "/home/nguyen/miniconda3/envs/uit-ds/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/nguyen/miniconda3/envs/uit-ds/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/nguyen/miniconda3/envs/uit-ds/lib/python3.10/site-packages/accelerate/hooks.py", line 170, in new_forward
    output = module._old_forward(*args, **kwargs)
  File "/home/nguyen/miniconda3/envs/uit-ds/lib/python3.10/site-packages/transformers/models/qwen2_vl/modeling_qwen2_vl.py", line 431, in forward
    hidden_states = hidden_states + self.attn(
  File "/home/nguyen/miniconda3/envs/uit-ds/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/nguyen/miniconda3/envs/uit-ds/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/nguyen/miniconda3/envs/uit-ds/lib/python3.10/site-packages/accelerate/hooks.py", line 170, in new_forward
    output = module._old_forward(*args, **kwargs)
  File "/home/nguyen/miniconda3/envs/uit-ds/lib/python3.10/site-packages/transformers/models/qwen2_vl/modeling_qwen2_vl.py", line 404, in forward
    attn_output = F.scaled_dot_product_attention(q, k, v, attention_mask, dropout_p=0.0)
torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 9.07 GiB. GPU 0 has a total capacity of 23.68 GiB of which 5.61 GiB is free. Including non-PyTorch memory, this process has 18.07 GiB memory in use. Of the allocated memory 17.57 GiB is allocated by PyTorch, and 197.16 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)

